language: php
sudo: false
branches:
  only:
    - master
    - /^([0-9]+\.){1,2}(x|[0-9]+)$/

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - dev@tim-schreiner.de

before_install:
  - if php -i | grep -v TRAVIS_CMD | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

install:
  - |
    composer require \
      typo3/cms-backend="$TYPO3_VERSION" \
      typo3/cms-recordlist="$TYPO3_VERSION" \
      typo3/cms-core="$TYPO3_VERSION" \
      typo3/cms-extbase="$TYPO3_VERSION" \
      typo3/cms-extensionmanager="$TYPO3_VERSION" \
      typo3/cms-fluid="$TYPO3_VERSION" \
      typo3/cms-frontend="$TYPO3_VERSION" \
      typo3/cms-install="$TYPO3_VERSION" \
      typo3/cms-scheduler="$TYPO3_VERSION" \
      typo3/cms-recordlist="$TYPO3_VERSION"
  - git checkout composer.json

script:
  - |
    echo;
    echo "Create LocalConfiguration.php";
    cat > .Build/Web/typo3conf/LocalConfiguration.php << EOF
    <?php
    return [];
    EOF
  - >
    echo;
    echo "Running php lint...";
    find . -name \*.php ! -path "./.Build/*" -exec php -d display_errors=stderr -l {} > /dev/null \;
  - >
    echo;
    echo "Running unit tests...";
    .Build/bin/phpunit --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/

jobs:
  allow_failures:
    - env: TYPO3_VERSION="dev-master"
  include:
    - stage: test
      php: 7.4
      env: TYPO3_VERSION="dev-master"
    - stage: test
      php: 7.3
      env: TYPO3_VERSION="dev-master"
    - stage: test
      php: 7.2
      env: TYPO3_VERSION="dev-master"
    - stage: test
      php: 7.4
      env: TYPO3_VERSION="^10.4"
    - stage: test
      php: 7.3
      env: TYPO3_VERSION="^10.4"
    - stage: test
      php: 7.2
      env: TYPO3_VERSION="^10.4"
    - stage: test
      php: 7.4
      env: TYPO3_VERSION=^9.5
    - stage: test
      php: 7.3
      env: TYPO3_VERSION=^9.5
    - stage: test
      php: 7.2
      env: TYPO3_VERSION=^9.5
